import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:shared_preferences/shared_preferences.dart';

class AppLanguage extends ChangeNotifier {
  AppLanguage._();

  static final AppLanguage instance = AppLanguage._();
  static const String _storageKey = 'app_language_code';
  static const Map<String, String> _builderFallbackEn = <String, String>{
    'builder.newLevel': 'New Level',
    'builder.gameName': 'Game Name',
    'builder.save': 'Save',
    'builder.saveDraft': 'Save Draft',
    'builder.saving': 'Saving...',
    'builder.load': 'Load',
    'builder.import': 'Import',
    'builder.export': 'Export',
    'builder.publish': 'Publish',
    'builder.done': 'Done',
    'builder.cancel': 'Cancel',
    'builder.ok': 'OK',
    'builder.back': 'Back',
    'builder.overview': 'Overview',
    'builder.checklist': 'Checklist',
    'builder.hints': 'Hints',
    'builder.expectedOutput': 'Expected Output',
    'builder.resources': 'Resources',
    'builder.customSection': 'Custom Section',
    'builder.run': 'Run',
    'builder.stop': 'Stop',
    'builder.play': 'Play',
    'builder.reset': 'Reset',
    'builder.clear': 'Clear',
    'builder.delete': 'Delete',
    'builder.duplicate': 'Duplicate',
    'builder.settings': 'Settings',
    'builder.tools': 'Tools',
    'builder.palette': 'Palette',
    'builder.grid': 'Grid',
    'builder.instructions': 'Instructions',
    'builder.levelActions': 'Level Actions',
    'builder.levelInfo': 'Level Info',
    'builder.boardStyle': 'Board Style',
    'builder.playerDirection': 'Player Direction',
    'builder.chooseDifficulty': 'Choose Difficulty',
    'builder.clearLevel': 'Clear Level?',
    'builder.clearLevelBody':
        'This will remove all level items and solution blocks. This cannot be undone.',
    'builder.saveFailed': 'Save failed: {error}',
    'builder.loadFailed': 'Load failed: {error}',
    'builder.projectPublished': 'Project published',
    'builder.draftSaved': 'Draft saved',
    'builder.publishedSuccessfully': 'Game published successfully.',
    'builder.savedSuccessfully': 'Game saved successfully.',
    'builder.topViewPublishedSuccessfully':
        'Top view game published successfully.',
    'builder.topViewSavedSuccessfully': 'Top view game saved successfully.',
    'builder.scratch': 'Scratch Builder',
    'builder.frontView': 'Front View Builder',
    'builder.topView': 'Top View Builder',
    'builder.fourthDemo': 'Game Builder',
    'builder.ground': 'Ground',
    'builder.obstacle': 'Obstacle',
    'builder.player': 'Player',
    'builder.collect': 'Collect',
    'builder.goal': 'Goal',
    'builder.moveLeft': 'Move Left',
    'builder.moveRight': 'Move Right',
    'builder.remove': 'Remove',
    'builder.faceLeft': 'Face left',
    'builder.faceRight': 'Face right',
    'builder.startFacingUp': 'Start facing up',
    'builder.startFacingRight': 'Start facing right',
    'builder.startFacingDown': 'Start facing down',
    'builder.startFacingLeft': 'Start facing left',
    'builder.exportProjectJson': 'Export Project JSON',
    'builder.importProjectJson': 'Import Project JSON',
    'builder.projectJson': 'Project JSON',
    'builder.pasteJsonHere': 'Paste JSON here',
    'builder.welcomeGameBuilder': 'Welcome to the Game Builder',
    'builder.fourthOverviewContent':
        'Today we will learn how to create a game. The goal of the game is to move the player to get the banana. We will use the onKey function, which is called whenever you press a key on your keyboard. The image of the player character on the screen is called a sprite. The function step moves the sprite. Write inside the onKey function to move the player. Now let us start!',
    'builder.fourthInstructionsContent':
        'Use @step 1 inside @onKey. Once you are done, click the RUN button.',
    'builder.codeExample': 'Code Example',
    'builder.sprites': 'Sprites',
    'builder.widgets': 'Widgets',
    'builder.sounds': 'Sounds',
    'builder.game': 'Game',
    'builder.addNew': 'Add New',
    'builder.spriteSettings': 'Sprite Settings',
    'builder.widgetSettings': 'Widget Settings',
    'builder.soundSettings': 'Sound Settings',
    'builder.name': 'Name',
    'builder.text': 'Text',
    'builder.value': 'Value',
    'builder.opacity': 'Opacity',
    'builder.scale': 'Scale',
    'builder.rotation': 'Rotation',
    'builder.allowGravity': 'Allow Gravity',
    'builder.collideWorldBounds': 'Collide world bounds',
    'builder.collideOtherSprites': 'Collide other sprites',
    'builder.immovable': 'Immovable',
    'builder.show': 'Show',
    'builder.draggable': 'Draggable',
    'builder.direction': 'Direction',
    'builder.left': 'Left',
    'builder.right': 'Right',
    'builder.textColor': 'Text Color',
    'builder.background': 'Background',
    'builder.worldWidth': 'World width',
    'builder.worldHeight': 'World height',
    'builder.gravity': 'Gravity',
    'builder.physicsMode': 'Physics mode',
    'builder.cameraTarget': 'Camera target',
    'builder.tilemap': 'Tilemap',
    'builder.soundSettingsLabel': 'Sound settings',
    'builder.noSprite': 'No sprite',
    'builder.widget.counter': 'Counter',
    'builder.widget.timer': 'Timer',
    'builder.widget.clock': 'Clock',
    'builder.widget.button': 'Button',
    'builder.widget.dialog': 'Dialog',
    'builder.sound.collectSparkle': 'Collect sparkle',
    'builder.sound.jumpPop': 'Jump pop',
    'builder.sound.buttonClick': 'Button click',
    'builder.sound.successChime': 'Success chime',
    'builder.sound.timerTick': 'Timer tick',
    'builder.sound.warningBeep': 'Warning beep',
    'builder.command.step': 'Step',
    'builder.command.jump': 'Jump',
    'builder.command.getX': 'Get X',
    'builder.command.getY': 'Get Y',
    'builder.command.setX': 'Set X',
    'builder.command.setY': 'Set Y',
    'builder.command.setRotation': 'Set rotation',
    'builder.command.getRotation': 'Get rotation',
    'builder.command.setSpeed': 'Set speed',
    'builder.command.setAllowGravity': 'Set gravity',
    'builder.command.getDistanceFrom': 'Get distance',
    'builder.command.onStart': 'On start',
    'builder.command.onKey': 'On key',
    'builder.command.onCollide': 'On collide',
    'builder.command.onDragEnd': 'On drag end',
    'builder.command.onCollideWithWorldBounds': 'On world bounds',
    'builder.command.onSwipe': 'On swipe',
    'builder.command.onClick': 'On click',
    'builder.command.onAnimationEnd': 'On animation end',
    'builder.command.onAnimationLoop': 'On animation loop',
    'builder.command.onUpdate': 'On update',
    'builder.command.keyboard.left': 'Left key',
    'builder.command.keyboard.right': 'Right key',
    'builder.command.keyboard.up': 'Up key',
    'builder.command.keyboard.down': 'Down key',
    'builder.command.show': 'Show',
    'builder.command.hide': 'Hide',
    'builder.command.destroy': 'Destroy',
    'builder.command.disable': 'Disable',
    'builder.command.enable': 'Enable',
    'builder.command.setScale': 'Set scale',
    'builder.command.getScale': 'Get scale',
    'builder.command.say': 'Say',
    'builder.command.addAnimation': 'Add animation',
    'builder.command.startAnimation': 'Start animation',
    'builder.command.stopAnimation': 'Stop animation',
    'builder.command.game.setBackground': 'Set background',
    'builder.command.loop': 'Loop',
    'builder.command.times': 'Times',
    'builder.command.for': 'For each',
    'builder.command.until': 'Until',
    'builder.command.function': 'Function',
    'builder.command.if': 'If',
    'builder.command.if else': 'If else',
    'builder.command.return': 'Return',
    'builder.command.not': 'Not',
    'builder.command.and': 'And',
    'builder.command.or': 'Or',
    'builder.command.==': 'Equals',
    'builder.command.<': 'Less than',
    'builder.command.>': 'Greater than',
    'builder.command.+=': 'Add to',
    'builder.command.-=': 'Subtract from',
    'builder.title': 'Title',
    'builder.instructionBuilder': 'Instruction Builder',
    'builder.addSection': 'Add section',
    'builder.deleteSection': 'Delete section',
    'builder.dragToArrange': 'Drag to arrange',
    'builder.emptyInstructions':
        'Add sections for the learner to read before building.',
    'builder.examplePlaceholder': 'Write or paste an example.',
    'builder.startWriting': 'Start writing...',
    'builder.dragBlocksHere': 'Drag blocks here',
    'builder.describeLearnerBuild': 'Describe what the learner will build.',
    'builder.dragBlocksInstruction': 'Drag blocks into the workspace.',
    'builder.runProgramInstruction': 'Run your program.',
    'builder.draftPublishChecks': 'Draft saves without publish checks.',
    'builder.none': 'None',
    'builder.ready': 'Ready',
    'builder.playing': 'Playing',
    'builder.tool': 'Tool',
    'builder.selected': 'Selected',
    'builder.sizePreset': 'Size Preset',
    'builder.tileSize': 'Tile Size',
    'builder.collectables': 'Collectables',
    'builder.logicBlocks': 'Logic Blocks',
    'builder.runStatus': 'Run Status',
    'builder.eventsCategory': 'Events',
    'builder.motionCategory': 'Motion',
    'builder.looksCategory': 'Looks',
    'builder.soundCategory': 'Sound',
    'builder.sensingCategory': 'Sensing',
    'builder.variablesCategory': 'Variables',
    'builder.listsCategory': 'Lists',
    'builder.block.whenStartClicked': 'When Start Clicked',
    'builder.block.moveSteps': 'Move {steps} Steps',
    'builder.block.turnDegrees': 'Turn {degrees} deg',
    'builder.block.goTo': 'Go To X: {x} Y: {y}',
    'builder.block.say': 'Say {message}',
    'builder.block.think': 'Think {message}',
    'builder.block.wait': 'Wait {seconds} Second',
    'builder.block.repeat': 'Repeat {times} Times',
    'builder.block.keyPressed': 'Key {key} Pressed?',
    'builder.block.add': '{a} + {b}',
    'builder.block.greaterThan': '{a} > {b}',
    'builder.block.setVariable': 'Set {variable} To {value}',
    'builder.block.changeVariable': 'Change {variable} By {value}',
    'builder.key.space': 'space',
    'builder.key.up': 'up',
    'builder.key.down': 'down',
    'builder.key.left': 'left',
    'builder.key.right': 'right',
    'builder.loop': 'Loop',
    'builder.command': 'Command',
    'builder.jumpUp': 'Jump Up',
    'builder.climbUpLeft': 'Climb Up Left',
    'builder.climbUpRight': 'Climb Up Right',
    'builder.printSolution': 'Print Solution',
    'builder.levelCleared': 'Level cleared.',
    'builder.addRequiredItems': 'Add the required items before saving.',
    'builder.addRequiredItemsPrefix':
        'Add the required items before saving: {issues}',
    'builder.suggested': 'Suggested: ',
    'builder.easy': 'Easy',
    'builder.medium': 'Medium',
    'builder.hard': 'Hard',
    'builder.useTurnAngles': 'Use Turn Angles',
    'builder.solutionBlocks': 'Solution Blocks',
    'builder.possibleSolution': 'Possible Solution',
    'builder.noSolutionBlocks': 'No solution blocks were provided',
    'builder.dropInstructionBlocks': 'Drop instruction blocks here',
    'builder.collectable': 'Collectable',
    'builder.chooseSprite': 'Choose Sprite',
    'builder.chooseWidget': 'Choose Widget',
    'builder.chooseSound': 'Choose Sound',
    'builder.stageTool': 'Stage tool',
    'builder.physics': 'Physics',
    'builder.layer': 'Layer',
    'builder.position': 'Position',
    'builder.opacityPercent': 'Opacity',
    'builder.color': 'Color',
    'builder.character': 'Character',
    'builder.initialDirection': 'Initial Direction',
    'builder.tileSizeDescription':
        '{label}: {tileSize} px squares, {columns} columns, {rows} rows.',
    'builder.gridPresetDescription':
        'Each preset refits the grid so it still fills the entire outer game rectangle.',
    'builder.clearLevelDescription':
        'Reset the level layout and logic. The bottom {rows} rows will stay ground in {label} mode.',
    'builder.logicHelp':
        'Add blocks, drag them into place, or tap a loop then add commands directly inside it.',
    'builder.logicLoopHelp':
        'The selected loop is ready. New blocks will be added inside it, or you can drag commands into any gap.',
    'builder.validation.addPlayer': 'Add a player before publishing.',
    'builder.validation.addGoal': 'Add a goal before publishing.',
    'builder.validation.addSolutionBlocks':
        'Add solution blocks before publishing.',
    'builder.validation.writeSolution':
        'Write a possible solution before publishing.',
    'builder.validation.solutionOutOfBounds':
        'The possible solution moves the player out of bounds.',
    'builder.validation.solutionCollectAll':
        'The possible solution must collect all collectables.',
    'builder.validation.solutionOnGoal':
        'The possible solution must finish on the goal.',
    'builder.gridSummary': 'Grid: {columns} columns x {rows} rows',
    'builder.rulerActiveHelp':
        'Ruler mode is active. Press a tile to start measuring, then press again to clear.',
    'builder.topViewHelp':
        'Drag pieces into the board, then write the path in the code panel.',
    'builder.selectRuler': 'Select ruler',
    'builder.deselectRuler': 'Deselect ruler',
    'builder.tiles': '{count} tiles',
    'builder.dropToDelete': 'Drop to delete',
    'builder.saveFailedGeneric': 'Failed to save game.',
    'builder.publishFailedGeneric': 'Failed to publish game.',
    'builder.loadTopViewFailedGeneric': 'Failed to load top view game.',
    'builder.dropHere': 'Drop here',
    'builder.dropHereToAdd': 'Drop here to add',
    'builder.gridSquareSize': 'Grid Square Size',
    'builder.jump': 'Jump',
    'builder.upLeftShort': 'Up-L',
    'builder.upRightShort': 'Up-R',
    'builder.leftShort': 'L',
    'builder.rightShort': 'R',
    'builder.upShort': 'UP',
    'builder.upLeftToken': 'UL',
    'builder.upRightToken': 'UR',
    'builder.codeBlock.step': 'step',
    'builder.codeBlock.turn': 'turn',
    'builder.codeBlock.up': 'up',
    'builder.codeBlock.down': 'down',
    'builder.codeBlock.left': 'left',
    'builder.codeBlock.right': 'right',
    'builder.character.polar': 'Polar',
    'builder.character.chicken': 'Chicken',
    'builder.character.duck': 'Duck',
    'builder.character.penguin': 'Penguin',
    'builder.character.reindeer': 'Reindeer',
    'builder.character.teddy': 'Teddy',
    'builder.collectable.banana': 'Banana',
    'builder.collectable.black-berry-dark': 'Black Berry Dark',
    'builder.collectable.black-berry-light': 'Black Berry Light',
    'builder.collectable.black-cherry': 'Black Cherry',
    'builder.collectable.coconut': 'Coconut',
    'builder.collectable.green-apple': 'Green Apple',
    'builder.collectable.green-grape': 'Green Grape',
    'builder.collectable.lemon': 'Lemon',
    'builder.collectable.lime': 'Lime',
    'builder.collectable.orange': 'Orange',
    'builder.collectable.peach': 'Peach',
    'builder.collectable.pear': 'Pear',
    'builder.collectable.plum': 'Plum',
    'builder.collectable.raspberry': 'Raspberry',
    'builder.collectable.red-apple': 'Red Apple',
    'builder.collectable.red-cherry': 'Red Cherry',
    'builder.collectable.red-grape': 'Red Grape',
    'builder.collectable.star-fruit': 'Star Fruit',
    'builder.collectable.strawberry': 'Strawberry',
    'builder.collectable.watermelon': 'Watermelon',
    'builder.topViewCharacter.cat': 'Cat',
    'builder.topViewCharacter.cow': 'Cow',
    'builder.topViewCharacter.dog': 'Dog',
    'builder.topViewCharacter.elephant': 'Elephant',
    'builder.topViewCharacter.horse': 'Horse',
    'builder.topViewBackground.grass': 'Grass',
    'builder.topViewBackground.sand': 'Sand',
    'builder.topViewObstacle.bush1': 'Bush 1',
    'builder.topViewObstacle.bush2': 'Bush 2',
    'builder.topViewObstacle.bush3': 'Bush 3',
    'builder.topViewObstacle.bush4': 'Bush 4',
    'builder.topViewObstacle.bush5': 'Bush 5',
    'builder.topViewObstacle.cactus1': 'Cactus 1',
    'builder.topViewObstacle.cactus2': 'Cactus 2',
    'builder.topViewObstacle.log1': 'Log 1',
    'builder.topViewObstacle.log2': 'Log 2',
    'builder.topViewObstacle.log3': 'Log 3',
    'builder.topViewObstacle.rock1': 'Rock 1',
    'builder.topViewObstacle.rock2': 'Rock 2',
  };

  static const Map<String, String> _builderFallbackAr = <String, String>{
    'builder.newLevel': 'مستوى جديد',
    'builder.gameName': 'اسم اللعبة',
    'builder.save': 'حفظ',
    'builder.saveDraft': 'حفظ كمسودة',
    'builder.saving': 'جار الحفظ...',
    'builder.load': 'تحميل',
    'builder.import': 'استيراد',
    'builder.export': 'تصدير',
    'builder.publish': 'نشر',
    'builder.done': 'تم',
    'builder.cancel': 'إلغاء',
    'builder.ok': 'موافق',
    'builder.back': 'رجوع',
    'builder.overview': 'نظرة عامة',
    'builder.checklist': 'قائمة التحقق',
    'builder.hints': 'تلميحات',
    'builder.expectedOutput': 'الناتج المتوقع',
    'builder.resources': 'الموارد',
    'builder.customSection': 'قسم مخصص',
    'builder.run': 'تشغيل',
    'builder.stop': 'إيقاف',
    'builder.play': 'تشغيل',
    'builder.reset': 'إعادة ضبط',
    'builder.clear': 'مسح',
    'builder.delete': 'حذف',
    'builder.duplicate': 'نسخ',
    'builder.settings': 'الإعدادات',
    'builder.tools': 'الأدوات',
    'builder.palette': 'لوحة الأدوات',
    'builder.grid': 'الشبكة',
    'builder.instructions': 'التعليمات',
    'builder.levelActions': 'إجراءات المستوى',
    'builder.levelInfo': 'معلومات المستوى',
    'builder.boardStyle': 'شكل اللوحة',
    'builder.playerDirection': 'اتجاه اللاعب',
    'builder.chooseDifficulty': 'اختر الصعوبة',
    'builder.clearLevel': 'مسح المستوى؟',
    'builder.clearLevelBody':
        'سيتم حذف عناصر المستوى وكتل الحل. لا يمكن التراجع عن ذلك.',
    'builder.saveFailed': 'فشل الحفظ: {error}',
    'builder.loadFailed': 'فشل التحميل: {error}',
    'builder.projectPublished': 'تم نشر المشروع',
    'builder.draftSaved': 'تم حفظ المسودة',
    'builder.publishedSuccessfully': 'تم نشر اللعبة بنجاح.',
    'builder.savedSuccessfully': 'تم حفظ اللعبة بنجاح.',
    'builder.topViewPublishedSuccessfully': 'تم نشر لعبة العرض العلوي بنجاح.',
    'builder.topViewSavedSuccessfully': 'تم حفظ لعبة العرض العلوي بنجاح.',
    'builder.scratch': 'باني سكراتش',
    'builder.frontView': 'باني العرض الجانبي',
    'builder.topView': 'باني العرض العلوي',
    'builder.fourthDemo': 'باني اللعبة',
    'builder.ground': 'أرض',
    'builder.obstacle': 'عائق',
    'builder.player': 'لاعب',
    'builder.collect': 'جمع',
    'builder.goal': 'هدف',
    'builder.moveLeft': 'تحريك لليسار',
    'builder.moveRight': 'تحريك لليمين',
    'builder.remove': 'إزالة',
    'builder.faceLeft': 'الاتجاه لليسار',
    'builder.faceRight': 'الاتجاه لليمين',
    'builder.startFacingUp': 'ابدأ للأعلى',
    'builder.startFacingRight': 'ابدأ لليمين',
    'builder.startFacingDown': 'ابدأ للأسفل',
    'builder.startFacingLeft': 'ابدأ لليسار',
    'builder.exportProjectJson': 'تصدير JSON المشروع',
    'builder.importProjectJson': 'استيراد JSON المشروع',
    'builder.projectJson': 'JSON المشروع',
    'builder.pasteJsonHere': 'الصق JSON هنا',
    'builder.welcomeGameBuilder': 'مرحبا في باني اللعبة',
    'builder.fourthOverviewContent':
        'اليوم سنتعلم كيف ننشئ لعبة. هدف اللعبة هو تحريك اللاعب ليحصل على الموزة. سنستخدم دالة onKey التي تعمل كلما ضغطت مفتاحا على لوحة المفاتيح. صورة اللاعب على الشاشة تسمى شخصية. الدالة step تحرك الشخصية. اكتب داخل دالة onKey لتحريك اللاعب. لنبدأ الآن!',
    'builder.fourthInstructionsContent':
        'استخدم @step 1 داخل @onKey. عندما تنتهي، اضغط زر التشغيل.',
    'builder.codeExample': 'مثال برمجي',
    'builder.sprites': 'الشخصيات',
    'builder.widgets': 'العناصر',
    'builder.sounds': 'الأصوات',
    'builder.game': 'اللعبة',
    'builder.addNew': 'إضافة جديد',
    'builder.spriteSettings': 'إعدادات الشخصية',
    'builder.widgetSettings': 'إعدادات العنصر',
    'builder.soundSettings': 'إعدادات الصوت',
    'builder.name': 'الاسم',
    'builder.text': 'النص',
    'builder.value': 'القيمة',
    'builder.opacity': 'الشفافية',
    'builder.scale': 'الحجم',
    'builder.rotation': 'الدوران',
    'builder.allowGravity': 'السماح بالجاذبية',
    'builder.collideWorldBounds': 'الاصطدام بحدود العالم',
    'builder.collideOtherSprites': 'الاصطدام بالشخصيات الأخرى',
    'builder.immovable': 'ثابت',
    'builder.show': 'إظهار',
    'builder.draggable': 'قابل للسحب',
    'builder.direction': 'الاتجاه',
    'builder.left': 'يسار',
    'builder.right': 'يمين',
    'builder.textColor': 'لون النص',
    'builder.background': 'الخلفية',
    'builder.worldWidth': 'عرض العالم',
    'builder.worldHeight': 'ارتفاع العالم',
    'builder.gravity': 'الجاذبية',
    'builder.physicsMode': 'نمط الفيزياء',
    'builder.cameraTarget': 'هدف الكاميرا',
    'builder.tilemap': 'خريطة البلاطات',
    'builder.soundSettingsLabel': 'إعدادات الصوت',
    'builder.noSprite': 'لا توجد شخصية',
    'builder.widget.counter': 'عداد',
    'builder.widget.timer': 'مؤقت',
    'builder.widget.clock': 'ساعة',
    'builder.widget.button': 'زر',
    'builder.widget.dialog': 'حوار',
    'builder.sound.collectSparkle': 'لمعة الجمع',
    'builder.sound.jumpPop': 'صوت القفز',
    'builder.sound.buttonClick': 'نقرة زر',
    'builder.sound.successChime': 'نغمة النجاح',
    'builder.sound.timerTick': 'دقة المؤقت',
    'builder.sound.warningBeep': 'تنبيه تحذير',
    'builder.command.step': 'خطوة',
    'builder.command.jump': 'قفز',
    'builder.command.getX': 'قراءة X',
    'builder.command.getY': 'قراءة Y',
    'builder.command.setX': 'تعيين X',
    'builder.command.setY': 'تعيين Y',
    'builder.command.setRotation': 'تعيين الدوران',
    'builder.command.getRotation': 'قراءة الدوران',
    'builder.command.setSpeed': 'تعيين السرعة',
    'builder.command.setAllowGravity': 'تعيين الجاذبية',
    'builder.command.getDistanceFrom': 'قراءة المسافة',
    'builder.command.onStart': 'عند البدء',
    'builder.command.onKey': 'عند الضغط',
    'builder.command.onCollide': 'عند الاصطدام',
    'builder.command.onDragEnd': 'عند انتهاء السحب',
    'builder.command.onCollideWithWorldBounds': 'عند حدود العالم',
    'builder.command.onSwipe': 'عند السحب بالإصبع',
    'builder.command.onClick': 'عند النقر',
    'builder.command.onAnimationEnd': 'عند انتهاء الحركة',
    'builder.command.onAnimationLoop': 'عند تكرار الحركة',
    'builder.command.onUpdate': 'عند التحديث',
    'builder.command.keyboard.left': 'مفتاح اليسار',
    'builder.command.keyboard.right': 'مفتاح اليمين',
    'builder.command.keyboard.up': 'مفتاح الأعلى',
    'builder.command.keyboard.down': 'مفتاح الأسفل',
    'builder.command.show': 'إظهار',
    'builder.command.hide': 'إخفاء',
    'builder.command.destroy': 'تدمير',
    'builder.command.disable': 'تعطيل',
    'builder.command.enable': 'تفعيل',
    'builder.command.setScale': 'تعيين الحجم',
    'builder.command.getScale': 'قراءة الحجم',
    'builder.command.say': 'قل',
    'builder.command.addAnimation': 'إضافة حركة',
    'builder.command.startAnimation': 'بدء الحركة',
    'builder.command.stopAnimation': 'إيقاف الحركة',
    'builder.command.game.setBackground': 'تعيين الخلفية',
    'builder.command.loop': 'تكرار',
    'builder.command.times': 'مرات',
    'builder.command.for': 'لكل عنصر',
    'builder.command.until': 'حتى',
    'builder.command.function': 'دالة',
    'builder.command.if': 'إذا',
    'builder.command.if else': 'إذا وإلا',
    'builder.command.return': 'إرجاع',
    'builder.command.not': 'ليس',
    'builder.command.and': 'و',
    'builder.command.or': 'أو',
    'builder.command.==': 'يساوي',
    'builder.command.<': 'أصغر من',
    'builder.command.>': 'أكبر من',
    'builder.command.+=': 'زيادة',
    'builder.command.-=': 'إنقاص',
    'builder.title': 'العنوان',
    'builder.instructionBuilder': 'باني التعليمات',
    'builder.addSection': 'إضافة قسم',
    'builder.deleteSection': 'حذف القسم',
    'builder.dragToArrange': 'اسحب للترتيب',
    'builder.emptyInstructions': 'أضف أقساما ليقرأها المتعلم قبل البناء.',
    'builder.examplePlaceholder': 'اكتب أو الصق مثالا.',
    'builder.startWriting': 'ابدأ الكتابة...',
    'builder.dragBlocksHere': 'اسحب الكتل هنا',
    'builder.describeLearnerBuild': 'صف ما سيبنيه المتعلم.',
    'builder.dragBlocksInstruction': 'اسحب الكتل إلى مساحة العمل.',
    'builder.runProgramInstruction': 'شغل برنامجك.',
    'builder.draftPublishChecks': 'يتم حفظ المسودة بدون فحوصات النشر.',
    'builder.none': 'لا شيء',
    'builder.ready': 'جاهز',
    'builder.playing': 'قيد التشغيل',
    'builder.tool': 'الأداة',
    'builder.selected': 'المحدد',
    'builder.sizePreset': 'حجم الشبكة',
    'builder.tileSize': 'حجم البلاطة',
    'builder.collectables': 'العناصر القابلة للجمع',
    'builder.logicBlocks': 'كتل المنطق',
    'builder.runStatus': 'حالة التشغيل',
    'builder.eventsCategory': 'الأحداث',
    'builder.motionCategory': 'الحركة',
    'builder.looksCategory': 'المظهر',
    'builder.soundCategory': 'الصوت',
    'builder.sensingCategory': 'الاستشعار',
    'builder.variablesCategory': 'المتغيرات',
    'builder.listsCategory': 'القوائم',
    'builder.block.whenStartClicked': 'عند بدء التشغيل',
    'builder.block.moveSteps': 'تحرك {steps} خطوة',
    'builder.block.turnDegrees': 'استدر {degrees} درجة',
    'builder.block.goTo': 'اذهب إلى X: {x} Y: {y}',
    'builder.block.say': 'قل {message}',
    'builder.block.think': 'فكر {message}',
    'builder.block.wait': 'انتظر {seconds} ثانية',
    'builder.block.repeat': 'كرر {times} مرات',
    'builder.block.keyPressed': 'هل ضغط المفتاح {key}؟',
    'builder.block.add': '{a} + {b}',
    'builder.block.greaterThan': '{a} > {b}',
    'builder.block.setVariable': 'اجعل {variable} يساوي {value}',
    'builder.block.changeVariable': 'غير {variable} بمقدار {value}',
    'builder.key.space': 'مسافة',
    'builder.key.up': 'أعلى',
    'builder.key.down': 'أسفل',
    'builder.key.left': 'يسار',
    'builder.key.right': 'يمين',
    'builder.loop': 'تكرار',
    'builder.command': 'أمر',
    'builder.jumpUp': 'اقفز للأعلى',
    'builder.climbUpLeft': 'تسلق للأعلى يسارا',
    'builder.climbUpRight': 'تسلق للأعلى يمينا',
    'builder.printSolution': 'طباعة الحل',
    'builder.levelCleared': 'تم مسح المستوى.',
    'builder.addRequiredItems': 'أضف العناصر المطلوبة قبل الحفظ.',
    'builder.addRequiredItemsPrefix':
        'أضف العناصر المطلوبة قبل الحفظ: {issues}',
    'builder.suggested': 'المقترح: ',
    'builder.easy': 'سهل',
    'builder.medium': 'متوسط',
    'builder.hard': 'صعب',
    'builder.useTurnAngles': 'استخدام زوايا الدوران',
    'builder.solutionBlocks': 'كتل الحل',
    'builder.possibleSolution': 'حل ممكن',
    'builder.noSolutionBlocks': 'لم يتم توفير كتل حل',
    'builder.dropInstructionBlocks': 'أسقط كتل التعليمات هنا',
    'builder.collectable': 'عنصر قابل للجمع',
    'builder.chooseSprite': 'اختر شخصية',
    'builder.chooseWidget': 'اختر عنصرا',
    'builder.chooseSound': 'اختر صوتا',
    'builder.stageTool': 'أداة المسرح',
    'builder.physics': 'الفيزياء',
    'builder.layer': 'الطبقة',
    'builder.position': 'الموقع',
    'builder.opacityPercent': 'الشفافية',
    'builder.color': 'اللون',
    'builder.character': 'الشخصية',
    'builder.initialDirection': 'الاتجاه الابتدائي',
    'builder.tileSizeDescription':
        '{label}: مربعات {tileSize} بكسل، {columns} أعمدة، {rows} صفوف.',
    'builder.gridPresetDescription':
        'كل خيار يعيد ضبط الشبكة حتى تملأ مستطيل اللعبة بالكامل.',
    'builder.clearLevelDescription':
        'إعادة ضبط تخطيط المستوى والمنطق. ستبقى الصفوف السفلية وعددها {rows} أرضا في وضع {label}.',
    'builder.logicHelp':
        'أضف الكتل واسحبها إلى مكانها، أو اضغط على تكرار ثم أضف الأوامر داخله.',
    'builder.logicLoopHelp':
        'التكرار المحدد جاهز. ستتم إضافة الكتل الجديدة داخله، أو يمكنك سحب الأوامر إلى أي فراغ.',
    'builder.validation.addPlayer': 'أضف لاعبا قبل النشر.',
    'builder.validation.addGoal': 'أضف هدفا قبل النشر.',
    'builder.validation.addSolutionBlocks': 'أضف كتل الحل قبل النشر.',
    'builder.validation.writeSolution': 'اكتب حلا ممكنا قبل النشر.',
    'builder.validation.solutionOutOfBounds':
        'الحل الممكن يحرك اللاعب خارج الحدود.',
    'builder.validation.solutionCollectAll':
        'يجب أن يجمع الحل الممكن كل العناصر.',
    'builder.validation.solutionOnGoal': 'يجب أن ينتهي الحل الممكن عند الهدف.',
    'builder.gridSummary': 'الشبكة: {columns} أعمدة x {rows} صفوف',
    'builder.rulerActiveHelp':
        'وضع المسطرة نشط. اضغط على بلاطة لبدء القياس، ثم اضغط مرة أخرى للمسح.',
    'builder.topViewHelp':
        'اسحب القطع إلى اللوحة، ثم اكتب المسار في لوحة الكود.',
    'builder.selectRuler': 'اختيار المسطرة',
    'builder.deselectRuler': 'إلغاء اختيار المسطرة',
    'builder.tiles': '{count} بلاطات',
    'builder.dropToDelete': 'أفلت للحذف',
    'builder.saveFailedGeneric': 'فشل حفظ اللعبة.',
    'builder.publishFailedGeneric': 'فشل نشر اللعبة.',
    'builder.loadTopViewFailedGeneric': 'فشل تحميل لعبة العرض العلوي.',
    'builder.dropHere': 'أفلت هنا',
    'builder.dropHereToAdd': 'أفلت هنا للإضافة',
    'builder.gridSquareSize': 'حجم مربع الشبكة',
    'builder.jump': 'قفز',
    'builder.upLeftShort': 'أعلى-يسار',
    'builder.upRightShort': 'أعلى-يمين',
    'builder.leftShort': 'ي',
    'builder.rightShort': 'م',
    'builder.upShort': 'أعلى',
    'builder.upLeftToken': 'أ-ي',
    'builder.upRightToken': 'أ-م',
    'builder.codeBlock.step': 'خطوة',
    'builder.codeBlock.turn': 'دوران',
    'builder.codeBlock.up': 'أعلى',
    'builder.codeBlock.down': 'أسفل',
    'builder.codeBlock.left': 'يسار',
    'builder.codeBlock.right': 'يمين',
    'builder.character.polar': 'باندا',
    'builder.character.chicken': 'دجاجة',
    'builder.character.duck': 'بطة',
    'builder.character.penguin': 'بطريق',
    'builder.character.reindeer': 'رنة',
    'builder.character.teddy': 'دب',
    'builder.collectable.banana': 'موزة',
    'builder.collectable.black-berry-dark': 'توت أسود داكن',
    'builder.collectable.black-berry-light': 'توت أسود فاتح',
    'builder.collectable.black-cherry': 'كرز أسود',
    'builder.collectable.coconut': 'جوز هند',
    'builder.collectable.green-apple': 'تفاحة خضراء',
    'builder.collectable.green-grape': 'عنب أخضر',
    'builder.collectable.lemon': 'ليمون أصفر',
    'builder.collectable.lime': 'ليمون أخضر',
    'builder.collectable.orange': 'برتقال',
    'builder.collectable.peach': 'خوخ',
    'builder.collectable.pear': 'إجاص',
    'builder.collectable.plum': 'برقوق',
    'builder.collectable.raspberry': 'توت عليق',
    'builder.collectable.red-apple': 'تفاحة حمراء',
    'builder.collectable.red-cherry': 'كرز أحمر',
    'builder.collectable.red-grape': 'عنب أحمر',
    'builder.collectable.star-fruit': 'فاكهة النجمة',
    'builder.collectable.strawberry': 'فراولة',
    'builder.collectable.watermelon': 'بطيخ',
    'builder.topViewCharacter.cat': 'قطة',
    'builder.topViewCharacter.cow': 'بقرة',
    'builder.topViewCharacter.dog': 'كلب',
    'builder.topViewCharacter.elephant': 'فيل',
    'builder.topViewCharacter.horse': 'حصان',
    'builder.topViewBackground.grass': 'عشب',
    'builder.topViewBackground.sand': 'رمل',
    'builder.topViewObstacle.bush1': 'شجيرة 1',
    'builder.topViewObstacle.bush2': 'شجيرة 2',
    'builder.topViewObstacle.bush3': 'شجيرة 3',
    'builder.topViewObstacle.bush4': 'شجيرة 4',
    'builder.topViewObstacle.bush5': 'شجيرة 5',
    'builder.topViewObstacle.cactus1': 'صبار 1',
    'builder.topViewObstacle.cactus2': 'صبار 2',
    'builder.topViewObstacle.log1': 'جذع 1',
    'builder.topViewObstacle.log2': 'جذع 2',
    'builder.topViewObstacle.log3': 'جذع 3',
    'builder.topViewObstacle.rock1': 'صخرة 1',
    'builder.topViewObstacle.rock2': 'صخرة 2',
  };

  Locale _locale = const Locale('en');
  Map<String, String> _translations = {};
  Map<String, String> _englishTranslations = {
    ..._builderFallbackEn,
  };

  Locale get locale => _locale;
  bool get isArabic => _locale.languageCode == 'ar';
  TextDirection get textDirection =>
      isArabic ? TextDirection.rtl : TextDirection.ltr;

  Future<void> load() async {
    final prefs = await SharedPreferences.getInstance();
    final code = prefs.getString(_storageKey) ?? 'en';
    await setLanguage(code, persist: false);
  }

  Future<void> setLanguage(String code, {bool persist = true}) async {
    final normalizedCode = code == 'ar' ? 'ar' : 'en';
    final englishRawJson = await rootBundle.loadString('assets/i18n/en.json');
    final rawJson = await rootBundle.loadString(
      'assets/i18n/$normalizedCode.json',
    );
    final englishDecoded = jsonDecode(englishRawJson) as Map<String, dynamic>;
    final decoded = jsonDecode(rawJson) as Map<String, dynamic>;
    final englishBuilderDecoded = await _loadOptionalTranslations(
      'assets/i18n/builders_en.json',
    );
    final builderDecoded = await _loadOptionalTranslations(
      'assets/i18n/builders_$normalizedCode.json',
    );
    final builderFallback = normalizedCode == 'ar'
        ? _builderFallbackAr
        : _builderFallbackEn;

    _locale = Locale(normalizedCode);
    _englishTranslations = <String, dynamic>{
      ...englishDecoded,
      ..._builderFallbackEn,
      ...englishBuilderDecoded,
    }.map((key, value) => MapEntry(key, value.toString()));
    _translations = <String, dynamic>{
      ...decoded,
      ...builderFallback,
      ...builderDecoded,
    }.map((key, value) => MapEntry(key, value.toString()));

    if (persist) {
      final prefs = await SharedPreferences.getInstance();
      await prefs.setString(_storageKey, normalizedCode);
    }

    notifyListeners();
  }

  String t(String key, {Map<String, String> params = const {}}) {
    var value = _rawTranslationForKey(key) ?? key;

    for (final entry in params.entries) {
      value = value.replaceAll('{${entry.key}}', entry.value);
    }

    return value;
  }

  String tr(
    String key,
    String fallback, {
    Map<String, String> params = const {},
  }) {
    var value = _rawTranslationForKey(key) ?? fallback;

    for (final entry in params.entries) {
      value = value.replaceAll('{${entry.key}}', entry.value);
    }

    return value;
  }

  String? _rawTranslationForKey(String key) {
    if (key.startsWith('builder.')) {
      return _englishTranslations[key] ?? _builderFallbackEn[key] ?? key;
    }

    return _translations[key];
  }

  Future<Map<String, dynamic>> _loadOptionalTranslations(
    String assetPath,
  ) async {
    try {
      final rawJson = await rootBundle.loadString(assetPath);
      return jsonDecode(rawJson) as Map<String, dynamic>;
    } catch (_) {
      return const <String, dynamic>{};
    }
  }

  static AppLanguage of(BuildContext context) {
    final scope = context.dependOnInheritedWidgetOfExactType<_LanguageScope>();
    return scope?.notifier ?? instance;
  }
}

class LanguageScope extends StatelessWidget {
  const LanguageScope({super.key, required this.child});

  final Widget child;

  @override
  Widget build(BuildContext context) {
    return _LanguageScope(notifier: AppLanguage.instance, child: child);
  }
}

class _LanguageScope extends InheritedNotifier<AppLanguage> {
  const _LanguageScope({
    required AppLanguage super.notifier,
    required super.child,
  });
}
